### ISSUE TITLE
Bug in Manual extrinsics with user input multiplied by the chain decimals erroneously

### ISSUE THREAD

**Issue by Tbaut** [polkasafe/polkasafe-ui#302]
This line assumes all Compact `u16`, `u32`... are balances, and the user input is expected to be in the chain's token, hence multiplied by 10^(decimals): https://github.com/polkasafe/polkasafe-ui/blame/main/src/components/SendFunds/ManualExtrinsics.tsx#L285

However, this assumption is wrong, and you end up transforming and multiplying by 1000000000 an input that should not be touched!
e.g for `proxy.killPure`, the `height` and `extIndex`.

![image](https://github.com/polkasafe/polkasafe-ui/assets/33178835/e6cfe40e-46f8-477b-b544-01b1f62d7b44)

cf: https://github.com/ChainSafe/Multix/pull/312#pullrequestreview-1585758044

**Comment by aadarsh012** [comment]
Thank  you for finding out this bug, this will be fixed asap and will be updated here.

**Comment by aadarsh012** [comment]
Fixed with PR https://github.com/polkasafe/polkasafe-ui/pull/303
